version: 2
services:
  - type: web
    name: sms-appointment-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: CALENDLY_API_TOKEN
        sync: false
      - key: CALENDLY_USER_URI
        sync: false
      - key: LANGSMITH_API_KEY
        sync: false
      - key: LANGSMITH_PROJECT_NAME
        value: sms-appointment-booking
      - key: LANGSMITH_ENDPOINT
        value: https://api.smith.langchain.com
      - key: DEBUG_MODE
        value: false
      - key: MAX_RETRY_ATTEMPTS
        value: 3
      - key: SESSION_TIMEOUT
        value: 3600
      - key: LOG_LEVEL
        value: INFO
      - key: PORT
        value: 10000
    healthCheckPath: /health
